In [2]:
import pandas as pd
import numpy as np

In [4]:
# Create an array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(3,5)

array([5, 5, 5])

In [12]:
# Create an array from the list
a = np.array([1,2,3,5,7,8,10])
a[2] = 44
a

array([ 1,  2, 44,  5,  7,  8, 10])

In [14]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
# Create a space btwn arguments
np.linspace(0,1000,11)

array([   0.,  100.,  200.,  300.,  400.,  500.,  600.,  700.,  800.,
        900., 1000.])

In [18]:
# Multi-dim arrays rows,cols
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
n = np.array([[1,2,3], [4,5,6], [7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
n_2 = n[0,1]
n_2 

np.int64(2)

In [22]:
r_1 = n[0]
r_1

array([1, 2, 3])

In [23]:
n[0] = [1,1,1]
n

array([[1, 1, 1],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
# Random std uniformed distribution, to reproduce add the seed
np.random.seed(10)
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [27]:
# Std normal distr
np.random.seed(10)
100 * np.random.randn(5,2)

array([[ 133.15865041,   71.52789744],
       [-154.54002921,   -0.83838499],
       [  62.13359739,  -72.00855607],
       [  26.55115857,   10.85485257],
       [   0.42914309,  -17.46002106]])

In [28]:
# Random int
np.random.seed(10)
100 * np.random.randint(low=0,high=100, size=(5,2))

array([[ 900, 1500],
       [6400, 2800],
       [8900, 9300],
       [2900,  800],
       [7300,    0]])

In [30]:
# Operations, instead of the for-loop with np we can proceed as it is
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [33]:
b = (10 + (a * 2)) ** 2
b

array([100, 144, 196, 256, 324])

In [34]:
a + b

array([100, 145, 198, 259, 328])

In [35]:
# Comparison ops
a >= 2

array([False, False,  True,  True,  True])

In [38]:
# Returns all True elements
a[a<b]

array([0, 1, 2, 3, 4])

In [39]:
# Summarized operations
a.min()

np.int64(0)

In [40]:
a.max()

np.int64(4)

In [41]:
a.sum()

np.int64(10)

In [42]:
a.mean()

np.float64(2.0)

In [65]:
np.exp(a) #log and sqrt as well

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [63]:
a.std()

np.float64(1.4142135623730951)

# Linear Algebra Recap

The scalar vector product, also known as scalar multiplication, is a fundamental operation in linear algebra. 
It involves multiplying a scalar (a single number) by each component of a vector.
To perform a scalar vector product, you simply multiply the scalar by each element of the vector separately. 
For example, if we have a scalar c and a vector v, the scalar vector product is denoted as c * v and is calculated as:

c * v = (c * v₁, c * v₂, c * v₃, ..., c * vₙ)


In [45]:
u = np.array([2, 4, 5, 6])
v = 2 * u
# Output:  array([4, 8, 10, 12])

In [46]:
u + v

array([ 6, 12, 15, 18])

## Dot product

vector * vector mult

u · v = u₁v₁ + u₂v₂ + u₃v₃ + … + uₙvₙ

An important use case is the dot product between a transposed vector and a vector, e.g. vTu.




In [98]:
# row * column
u = np.array([2, 4, 5, 6])
v = np.array([1,1,1,1])

In [121]:
# Important to check the shape of vectors
def vec_vec_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    
    result = 0.0
    n = u.shape[0]
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [128]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])
# Output: 14.0
vec_vec_multiplication(u,v)

np.float64(14.0)

In [129]:
u.dot(v)

np.int64(14)

In [124]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])
 
v = np.array([1, 0, 0, 2])

In [133]:
#num of cols in matrix = num of rows in vector
def matrix_vector_mult(U, v):
    assert U.shape[1] == v.shape[0]

    n_rows = U.shape[0] # Size of the result vector

    result = np.zeros(n_rows)
    print(result)
    # go through each row, multiply element by element and sum up

    for i in range(n_rows):
        result[i] = vec_vec_multiplication(U[i],v)
    return result

In [134]:
v.shape

(4,)

In [136]:
matrix_vector_mult(U,v)

[0. 0. 0.]


array([14.,  5.,  5.])

In [137]:
U.dot(v)

array([14,  5,  5])

In [138]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

V = np.array([
    [1, 1,   2],
    [0, 0.5, 1],
    [0, 2,   1],
    [2, 1,   0]
])
""" result_matrix = [14, 20, 13],
                    [5, 6,   5],
                    [5, 8.5, 9"""

' result_matrix = [14, 20, 13],\n                    [5, 6,   5],\n                    [5, 8.5, 9'

In [139]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [142]:
def matrix_matrix_mult(U,V):
    assert U.shape[1] == V.shape[0]

    n_result_rows = U.shape[0]
    n_result_cols = V.shape[1]

    result = np.zeros((n_result_rows, n_result_cols))
    for i in range(n_result_cols):
        vi = V[:,i]
        Uvi = matrix_vector_mult(U, vi)
        print(Uvi)
        result[:,i] = Uvi
    return result

In [141]:
U[:,0]

array([2, 1, 3])

In [144]:
matrix_matrix_mult(U,V)

[0. 0. 0.]
[14.  5.  5.]
[0. 0. 0.]
[20.   6.   8.5]
[0. 0. 0.]
[13.  5.  9.]


array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [145]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

In [146]:
I = np.eye(3)

In [147]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [149]:
# When mult.by an identity matrix we are getting the same matrix back
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inversed matrix
V.dot(Inversed_V) = Identity_V

Only square n_rows=n_cols can be inversed

In [156]:
# Let's take 3 rows of V matrix bcause it has 3 columns
Square_V = V[[0,1,2]]
Square_V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [157]:
Inversed_Square_V = np.linalg.inv(Square_V)
Inversed_Square_V 

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [158]:
Inversed_Square_V.dot(Square_V)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

As a result we have an identity matrix